

//Data for handymen services - e.g - plumbing
const servicesData = {
    plumbing: [
        'Emergency Leaks', 'Drain Cleaning', 'Water Heater Repair',
        'Bathroom Installations', 'Pipe Repair', 'Boiler Servicing',
        'Fixture Installation', 'Leak Detection', 'General Plumbing'
    ],
    carpentry: [
        'Furniture Assembly', 'Custom Cabinets', 'Door Installation',
        'Window Repair', 'Deck Building', 'Flooring Installation',
        'Custom Shelving'
    ],
    electrical: [
        'Electrical Wiring', 'Light Fixture Installation', 'Outlet Repair',
        'Circuit Breaker Issues', 'Appliance Hookups', 'Electrical Inspections'
    ],
    painting: [
        'Interior Painting', 'Exterior Painting', 'Wallpaper Installation',
        'Drywall Repair', 'Moulding & Trim Painting', 'Commercial Painting'
    ],
    cleaning: [
        'Residential Cleaning', 'Commercial Cleaning', 'Deep Cleaning',
        'Window Cleaning', 'Carpet Cleaning', 'Post-Construction Cleaning'
    ],
    blacksmithing: [
        'Custom Metalwork', 'Wrought Iron Gates', 'Railings & Balconies',
        'Architectural Metalwork', 'Repairs & Restoration', 'Decorative Items'
    ],
    other: [
        'Please specify in description'
    ]
};

// Data for countries and localities
const countriesAndLocalities = {
    "Malta": ["Birkirkara", "Bormla (Cospicua)", "Fgura", "Floriana", "Fontana", "Għajnsielem", "Għarb", "Għargħur", "Għasri", "Għaxaq", "Gudja", "Gżira", "Ħamrun", "Iklin", "Isla (Senglea)", "Kalkara", "Kerċem", "Kirkop", "Lija", "Luqa", "Marsa", "Marsaskala", "Marsaxlokk", "Mdina", "Mellieħa", "Mosta", "Mqabba", "Msida", "Mtarfa", "Munxar", "Nadur", "Naxxar", "Paola", "Pembroke", "Pietà", "Qala", "Qormi", "Qrendi", "Rabat (Gozo)", "Rabat (Malta)", "Safi", "San Ġiljan (St. Julian's)", "San Lawrenz", "San Pawl il-Baħar (St. Paul's Bay)", "Sannat", "Santa Luċija", "Santa Venera", "Siġġiewi", "Sliema", "Swieqi", "Ta' Xbiex", "Tarxien", "Valletta", "Xagħra", "Xewkija", "Xgħajra", "Żabbar", "Żebbuġ (Gozo)", "Żebbuġ (Malta)", "Żejtun", "Żurrieq"],
    "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa", "Bologna", "Florence", "Bari", "Catania"],
    "United Kingdom": ["London", "Manchester", "Birmingham", "Glasgow", "Liverpool", "Bristol", "Edinburgh", "Leeds", "Sheffield", "Newcastle"]
};


// Country Dial Codes
const countryDialCodes = {
    "Malta": "+356",
    "Italy": "+39",
    "United Kingdom": "+44",
    "United States": "+1",
    "Canada": "+1",
    "Australia": "+61",
    "Germany": "+49",
    "France": "+33",
    "Spain": "+34",
    "Netherlands": "+31",
    "Belgium": "+32",
    "Sweden": "+46",
    "Norway": "+47",
    "Denmark": "+45",
    "Ireland": "+353",
    "Switzerland": "+41",
    "Austria": "+43",
    "Portugal": "+351",
    "Greece": "+30",
    "Cyprus": "+357",
    "Luxembourg": "+352",
    "Finland": "+358",
    "Iceland": "+354",
    "New Zealand": "+64",
    "South Africa": "+27",
    "Brazil": "+55",
    "Mexico": "+52",
    "Argentina": "+54",
    "Chile": "+56",
    "Colombia": "+57",
    "Peru": "+51",
    "Egypt": "+20",
    "Morocco": "+212",
    "United Arab Emirates": "+971",
    "Saudi Arabia": "+966",
    "Qatar": "+974",
    "Kuwait": "+965",
    "Bahrain": "+973",
    "Oman": "+968",
    "Turkey": "+90",
    "India": "+91",
    "China": "+86",
    "Japan": "+81",
    "South Korea": "+82",
    "Singapore": "+65",
    "Malaysia": "+60",
    "Thailand": "+66",
    "Indonesia": "+62",
    "Philippines": "+63",
    "Vietnam": "+84",
    "Russia": "+7",
    "Ukraine": "+380",
    "Poland": "+48",
    "Czech Republic": "+420",
    "Hungary": "+36",
    "Romania": "+40",
    "Bulgaria": "+359",
    "Croatia": "+385",
    "Serbia": "+381",
    "Bosnia and Herzegovina": "+387",
    "Slovenia": "+386",
    "Slovakia": "+421",
    "Lithuania": "+370",
    "Latvia": "+371",
    "Estonia": "+372",
    "Albania": "+355",
    "North Macedonia": "+389",
    "Montenegro": "+382",
    "Kosovo": "+383",
    "Moldova": "+373",
    "Georgia": "+995",
    "Armenia": "+374",
    "Azerbaijan": "+994",
    "Kazakhstan": "+7",
    "Uzbekistan": "+998",
    "Kyrgyzstan": "+996",
    "Tajikistan": "+992",
    "Turkmenistan": "+993",
    "Afghanistan": "+93",
    "Pakistan": "+92",
    "Bangladesh": "+880",
    "Sri Lanka": "+94",
    "Nepal": "+977",
    "Myanmar": "+95",
    "Laos": "+856",
    "Cambodia": "+855",
    "Mongolia": "+976",
    "Fiji": "+679",
    "Papua New Guinea": "+675",
    "Solomon Islands": "+677",
    "Vanuatu": "+678",
    "New Caledonia": "+687",
    "French Polynesia": "+689",
    "Egypt": "+20",
    "Nigeria": "+234",
    "Kenya": "+254",
    "Ethiopia": "+251",
    "Tanzania": "+255",
    "Uganda": "+256",
    "Ghana": "+233",
    "Ivory Coast": "+225",
    "Cameroon": "+237",
    "Angola": "+244",
    "Mozambique": "+258",
    "Madagascar": "+261",
    "Zambia": "+260",
    "Zimbabwe": "+263",
    "Botswana": "+267",
    "Namibia": "+264",
    "Congo (DRC)": "+243",
    "Sudan": "+249",
    "Algeria": "+213",
    "Tunisia": "+216",
    "Libya": "+218",
    "Chad": "+235",
    "Niger": "+227",
    "Mali": "+223",
    "Mauritania": "+222",
    "Senegal": "+221",
    "Guinea": "+224",
    "Burkina Faso": "+226",
    "Benin": "+229",
    "Togo": "+228",
    "Sierra Leone": "+232",
    "Liberia": "+231",
    "Gambia": "+220",
    "Cape Verde": "+238",
    "Sao Tome and Principe": "+239",
    "Equatorial Guinea": "+240",
    "Gabon": "+241",
    "Central African Republic": "+236",
    "Rwanda": "+250",
    "Burundi": "+257",
    "Djibouti": "+253",
    "Eritrea": "+291",
    "Somalia": "+252",
    "Comoros": "+269",
    "Seychelles": "+248",
    "Mauritius": "+230",
    "Malawi": "+265",
    "Lesotho": "+266",
    "Eswatini": "+268",
    "Reunion": "+262",
    "Mayotte": "+262",
    "South Sudan": "+211",
    "Venezuela": "+58",
    "Colombia": "+57",
    "Ecuador": "+593",
    "Bolivia": "+591",
    "Paraguay": "+595",
    "Uruguay": "+598",
    "Guyana": "+592",
    "Suriname": "+597",
    "French Guiana": "+594",
    "Cuba": "+53",
    "Jamaica": "+1-876",
    "Haiti": "+509",
    "Dominican Republic": "+1-809",
    "Puerto Rico": "+1-787",
    "Trinidad and Tobago": "+1-868",
    "Bahamas": "+1-242",
    "Barbados": "+1-246",
    "Saint Lucia": "+1-758",
    "Grenada": "+1-473",
    "Saint Vincent and the Grenadines": "+1-784",
    "Antigua and Barbuda": "+1-268",
    "Dominica": "+1-767",
    "Saint Kitts and Nevis": "+1-869",
    "Belize": "+501",
    "Guatemala": "+502",
    "El Salvador": "+503",
    "Honduras": "+504",
    "Nicaragua": "+505",
    "Costa Rica": "+506",
    "Panama": "+507",
    "Greenland": "+299",
    "Faroe Islands": "+298",
    "Gibraltar": "+350",
    "San Marino": "+378",
    "Vatican City": "+379",
    "Monaco": "+377",
    "Andorra": "+376",
    "Liechtenstein": "+423",
    "Maldives": "+960",
    "Brunei": "+673",
    "Timor-Leste": "+670",
    "Palau": "+680",
    "Micronesia": "+691",
    "Marshall Islands": "+692",
    "Nauru": "+674",
    "Kiribati": "+686",
    "Tuvalu": "+688",
    "Samoa": "+685",
    "Tonga": "+676",
    "Cook Islands": "+682",
    "Niue": "+683",
    "Tokelau": "+690",
    "Wallis and Futuna": "+681",
    "American Samoa": "+1-684",
    "Guam": "+1-671",
    "Northern Mariana Islands": "+1-670",
    "US Virgin Islands": "+1-340",
    "British Virgin Islands": "+1-284",
    "Anguilla": "+1-264",
    "Montserrat": "+1-664",
    "Turks and Caicos Islands": "+1-649",
    "Cayman Islands": "+1-345",
    "Bermuda": "+1-441",
    "Saint Pierre and Miquelon": "+508",
    "Falkland Islands": "+500",
    "South Georgia and the South Sandwich Islands": "+500",
    "Saint Helena, Ascension and Tristan da Cunha": "+290",
    "Norfolk Island": "+672",
    "Christmas Island": "+61",
    "Cocos (Keeling) Islands": "+61",
    "Pitcairn Islands": "+64",
    "Tokelau": "+690",
    "Heard Island and McDonald Islands": "+672",
    "French Southern and Antarctic Lands": "+262",
    "Bouvet Island": "+47",
    "Svalbard and Jan Mayen": "+47",
    "British Indian Ocean Territory": "+246",
    "United States Minor Outlying Islands": "+1",
    "Isle of Man": "+44",
    "Guernsey": "+44",
    "Jersey": "+44"
};



